# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RemoteDB
                                 A QGIS plugin
 Manage and open SSH connections to remote database servers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-16
        copyright            : (C) 2023 by Lymperis Efstathios
        email                : geo.elymperis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RemoteDB class from file RemoteDB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .remote_db import RemoteDB

    return RemoteDB(iface)
