on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: lymperis-e/publish-qgis-plugin-javascript-action
        with:
          release-zip-path: "./release/remote_db.zip"
          #qgis-version: "3.10"
          #qgis-repository: "https://plugins.qgis.org/plugins/plugins.xml?qgis=3.10"
          osgeo-id: ${{ secrets.OSGEO_ID }}
          osgeo-password: ${{ secrets.OSGEO_PASSWORD }}

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
