name: CI - Publish to QGIS plugins repository

on: [push]

jobs:
  publish-qgis-plugin:
    runs-on: ubuntu-latest
    name: A job to publish a QGIS plugin
    steps:
      - name: Post the plugin release to QGIS plugins repository
        id: publish
        uses: lymperis-e/publish-qgis-plugin-javascript-action@v1.6
        with:
          release-zip-path: "./release"
          osgeo-id: ${{ secrets.OSGEO_ID }}
          osgeo-password: ${{ secrets.OSGEO_PASSWORD }}
          #qgis-version: "3.10"
          #qgis-repository: "https://plugins.qgis.org/plugins/plugins.xml?qgis=3.10"

      - name: Get the output time
        run: echo "The time was ${{ steps.publish.outputs.published_url }}"
